[database]
connection = "postgresql://postgres:nostr@localhost:7500/nostr"

[network]
# Bind to this network address
address = "[::1]"

# Listen on this port
port = 50051

[plugins]
folder = "/home/me/nostr/plugins/"

# folder names in plugins folder
# eg. nostr/plugins/ | - spam
#                    | - verify
#                    | - etc.
# names = [ "spam", "verify" ]
names = [ "welcome" ]
