[network]
# Bind to this network address
address = "[::1]"

# Listen on this port
port = 50051

[plugins]
folder = "plugins"

# folder names in plugins folder
# eg. plugins/ | - spam
#              | - verify
#              | - etc.
# names = [ "spam", "verify" ]
names = [ "welcome" ]
